name: Update Submodules and Tokei Stats

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  update_submodules:
    name: Update Git Submodules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        run: |
          git submodule update --remote --merge

      - name: Commit updated submodules
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-update submodules'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  generate_stats:
    name: Generate Tokei Stats
    runs-on: ubuntu-latest
    needs: update_submodules  # runs after submodule update

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install Tokei
        run: |
          sudo apt-get update
          sudo apt-get install -y cargo
          cargo install tokei

      - name: Install jfq for jsonata
        run: npm install --global jfq

      - name: Install Gron
        run: sudo apt-get -y install gron

      - name: Generate Tokei Stats
        run: |
          tokei --output json |
          gron > toke_stats_gron.txt

      - name: Commit Tokei stats
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Alejandro Garcia
          author_email: agarciafdz@gmail.com
          message: 'Update code stats'
          add: 'docs/stats/tokei-stats.gron'
          github_token: ${{ secrets.GITHUB_TOKEN }}
