name: Update Submodules and Tokei Stats

on:
  schedule:
    - cron: "*/55 * * * *" # Run every 55 minutes
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main] # Also run on pushes to main branch

jobs:
  update_and_generate_stats:
    name: Update Submodules and Generate Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch full history for better submodule handling

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        id: update_submodules
        run: |
          echo "Checking for submodule updates..."
          git submodule update --recursive --remote

          # Check if there are any changes
          if git diff --quiet; then
            echo "submodule_changes=false" >> "$GITHUB_OUTPUT"
            echo "No submodule updates available"
          else
            echo "submodule_changes=true" >> "$GITHUB_OUTPUT"
            echo "Submodule updates found"
          fi

      - name: Commit submodule changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto-update: submodules"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install gron for JSON processing
        run: |
          sudo apt-get update
          sudo apt-get install -y gron

      - name: Make custom Tokei executable
        run: |
          chmod +x bin/tokei

      - name: Generate Tokei Stats
        run: |
          echo "Generating code statistics..."
          pwd
          ./bin/tokei
          ./bin/tokei --output json | gron > tokei-stats_gron.txt

      - name: Commit stats changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto-update: code statistics"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: "tokei-stats_gron.txt"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        run: |
          {
            echo "## Update Summary"
            echo "### Submodules"
            echo "- **Submodules updated:** ${{ steps.update_submodules.outputs.submodule_changes }}"
            if [ "${{ steps.update_submodules.outputs.submodule_changes }}" == "true" ]; then
              echo "- **Status:** Submodules were updated"
            else
              echo "- **Status:** No submodule changes detected"
            fi
            echo ""
            echo "### Code Statistics"
            echo "- **Stats changed:** ${{ steps.check_stats.outputs.stats_changed }}"
            echo "- **Total lines of code:** $(./bin/tokei --output json | jq -r '.Total.code')"
            echo "- **Languages detected:** $(./bin/tokei --output json | jq -r '.languages | length')"
          } >> "$GITHUB_STEP_SUMMARY"
