name: Update Submodules and Tokei Stats

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every half an hour
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [main]  # Also run on pushes to main branch

jobs:
  update_submodules:
    name: Update Git Submodules
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.update_submodules.outputs.changes }}
    
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history for better submodule handling

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        id: update_submodules
        run: |
          echo "Checking for submodule updates..."
          git submodule update --recursive --remote

          # Check if there are any changes
          if git diff --quiet; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
            echo "No submodule updates available"
          else
            echo "changes=true" >> "$GITHUB_OUTPUT"
            echo "Submodule updates found"
          fi

      - name: Commit submodule changes
        if: steps.update_submodules.outputs.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-update: submodules'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create submodule summary
        run: |
          {
            echo "## Submodule Update Summary"
            echo "- **Submodules updated:** ${{ steps.update_submodules.outputs.changes }}"
            if [ "${{ steps.update_submodules.outputs.changes }}" == "true" ]; then
              echo "- **Status:** Submodules were updated, stats generation will follow"
            else
              echo "- **Status:** No submodule changes detected, skipping stats generation"
            fi
          } >> "$GITHUB_STEP_SUMMARY"

  generate_stats:
    name: Generate Tokei Stats
    runs-on: ubuntu-latest
    needs: update_submodules
    if: needs.update_submodules.outputs.changes == 'true'
    
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main  # Ensure we get the latest main branch
          fetch-depth: 0

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Install tools for stats generation
        run: |
          # Install Tokei using pre-installed cargo
          cargo install tokei

          # Install gron for JSON processing
          sudo apt-get update
          sudo apt-get install -y gron

      - name: Generate Tokei Stats
        run: |
          echo "Generating code statistics..."
          tokei --output json | gron > tokei-stats_gron.txt

      - name: Check for stats changes
        id: check_stats
        run: |
          if git diff --quiet tokei-stats_gron.txt 2>/dev/null; then
            echo "stats_changed=false" >> "$GITHUB_OUTPUT"
            echo "No changes in code statistics"
          else
            echo "stats_changed=true" >> "$GITHUB_OUTPUT"
            echo "Code statistics have changed"
          fi

      - name: Commit stats changes
        if: steps.check_stats.outputs.stats_changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-update: code statistics'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: 'tokei-stats_gron.txt'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create stats summary
        run: |
          {
            echo "## Stats Generation Summary"
            echo "- **Stats changed:** ${{ steps.check_stats.outputs.stats_changed }}"
            echo ""
            echo "- **Total lines of code:** $(tokei --output json | jq -r '.Total.code')"
            echo "- **Languages detected:** $(tokei --output json | jq -r '.languages | length')"
          } >> "$GITHUB_STEP_SUMMARY"