name: Update Submodules and Tokei Stats

on:
  schedule:
    - cron: "*/55 * * * *"  # Run every 55 minutes
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [main]  # Also run on pushes to main branch

jobs:
  update_and_generate_stats:
    name: Update Submodules and Generate Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history for better submodule handling

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        id: update_submodules
        run: |
          echo "Checking for submodule updates..."
          git submodule update --recursive --remote

          # Check if there are any changes
          if git diff --quiet; then
            echo "submodule_changes=false" >> "$GITHUB_OUTPUT"
            echo "No submodule updates available"
          else
            echo "submodule_changes=true" >> "$GITHUB_OUTPUT"
            echo "Submodule updates found"
          fi

      - name: Commit submodule changes
        if: steps.update_submodules.outputs.submodule_changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-update: submodules'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools for stats generation
        run: |
          # Install Tokei using pre-installed cargo
          cargo install tokei

          # Install gron for JSON processing
          sudo apt-get update
          sudo apt-get install -y gron

      - name: Generate Tokei Stats
        run: |
          echo "Generating code statistics..."
          pwd
          tokei
          tokei --output json | gron > tokei-stats_gron_new.txt

      - name: Check for stats changes
        id: check_stats
        run: |
          # Compare new stats with existing stats (if it exists)
          if [ -f tokei-stats_gron.txt ] && cmp -s tokei-stats_gron.txt tokei-stats_gron_new.txt; then
            echo "stats_changed=false" >> "$GITHUB_OUTPUT"
            echo "No changes in code statistics"
            rm tokei-stats_gron_new.txt  # Clean up temp file
          else
            echo "stats_changed=true" >> "$GITHUB_OUTPUT"
            echo "Code statistics have changed"
            mv tokei-stats_gron_new.txt tokei-stats_gron.txt  # Replace with new stats
          fi

      - name: Commit stats changes
        if: steps.check_stats.outputs.stats_changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-update: code statistics'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          add: 'tokei-stats_gron.txt'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        run: |
          {
            echo "## Update Summary"
            echo "### Submodules"
            echo "- **Submodules updated:** ${{ steps.update_submodules.outputs.submodule_changes }}"
            if [ "${{ steps.update_submodules.outputs.submodule_changes }}" == "true" ]; then
              echo "- **Status:** Submodules were updated"
            else
              echo "- **Status:** No submodule changes detected"
            fi
            echo ""
            echo "### Code Statistics"
            echo "- **Stats changed:** ${{ steps.check_stats.outputs.stats_changed }}"
            echo "- **Total lines of code:** $(tokei --output json | jq -r '.Total.code')"
            echo "- **Languages detected:** $(tokei --output json | jq -r '.languages | length')"
          } >> "$GITHUB_STEP_SUMMARY"